name: Github CI

on:
  push:
    tags:
      - v**

jobs:
  run-build:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag' && contain(github.ref_name, 'production')
    steps:
      - name: Deploy APP to Production
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_7q4BeoXj82BW1Aw1SRrskdQZMho6/5yxvbU6LRe
